name: Build Flutter Windows

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-flutter:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Flutter SDK
        run: |
          git clone --depth 1 --branch stable https://github.com/flutter/flutter.git -q
          & "${{ github.workspace }}/flutter/bin/flutter" precache --windows

      - name: Build Flutter Windows
        run: |
          cd drama_remix_app
          ..\flutter\bin\flutter config --enable-windows-desktop
          ..\flutter\bin\flutter pub get
          ..\flutter\bin\flutter build windows --release

      - name: Upload Flutter Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-windows-exe
          path: drama_remix_app/build/windows/runner/Release/
          retention-days: 5
